# Generated by Django 4.2.2 on 2025-03-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_groupinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='IssueName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
